import streamlit as st
import os
from dotenv import load_dotenv
from typing import Annotated
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, AIMessage, ToolMessage
from langgraph.graph import StateGraph, START, END, MessagesState
from langgraph.prebuilt import ToolNode, tools_condition

# Initialize environment variables
load_dotenv()

# --- UI CONFIGURATION ---
st.set_page_config(
    page_title="LangGraph Agent Dashboard",
    page_icon="🕸️",
    layout="centered",
)

st.title("LangGraph Tool-Calling Agent")
st.markdown("Stateful agentic workflow with conditional tool routing.")

# Verify Environment
if not os.getenv("OPENAI_API_KEY"):
    st.error("Environment Error: OPENAI_API_KEY is not defined.")
    st.stop()

# --- TOOL DEFINITION ---
@tool
def calculate_multiply(a: int, b: int) -> int:
    """Multiply two integers together. Use this tool whenever you need to multiply numbers."""
    return a * b

# --- GRAPH INITIALIZATION ---
@st.cache_resource(show_spinner=False)
def initialize_graph():
    """Compiles the LangGraph workflow and caches the executable object."""
    tools = [calculate_multiply]
    
    # Initialize the LLM and bind the external tools to its execution context
    llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.1)
    llm_with_tools = llm.bind_tools(tools)

    def chatbot_node(state: MessagesState):
        """Passes the current conversation state to the LLM."""
        return {"messages": [llm_with_tools.invoke(state["messages"])]}

    # Build the StateGraph utilizing the built-in MessagesState schema
    graph_builder = StateGraph(MessagesState)
    
    # Add the primary chatbot node and the prebuilt Tool execution node
    graph_builder.add_node("chatbot", chatbot_node)
    graph_builder.add_node("tools", ToolNode(tools=tools))

    # Define the graph edges and conditional routing
    graph_builder.add_edge(START, "chatbot")
    # Route to 'tools' if the LLM decides to call a tool, otherwise route to END
    graph_builder.add_conditional_edges("chatbot", tools_condition)
    # Return to the chatbot after the tool executes to formulate the final answer
    graph_builder.add_edge("tools", "chatbot")
    
    return graph_builder.compile()

app_graph = initialize_graph()

# --- STATE MANAGEMENT ---
if "messages" not in st.session_state:
    st.session_state.messages = [
        AIMessage(content="System online. I am equipped with a multiplication tool. How can I assist you?")
    ]

# Render chat history (filtering out hidden ToolMessages for clean UI)
for msg in st.session_state.messages:
    if isinstance(msg, AIMessage) and not msg.tool_calls:
        with st.chat_message("assistant"):
            st.markdown(msg.content)
    elif isinstance(msg, HumanMessage):
        with st.chat_message("user"):
            st.markdown(msg.content)

# --- EXECUTION LOGIC ---
if prompt := st.chat_input("Ask a question or request a calculation..."):
    
    # Render user prompt
    st.session_state.messages.append(HumanMessage(content=prompt))
    with st.chat_message("user"):
        st.markdown(prompt)

    with st.chat_message("assistant"):
        with st.spinner("Agent computing path..."):
            try:
                # Execute the graph with the full conversational history
                result = app_graph.invoke({"messages": st.session_state.messages})
                
                # Update session state with the new messages generated by the graph
                # (This includes the AI's tool request, the tool execution result, and the final AI response)
                st.session_state.messages = result["messages"]
                
                # Render the final output
                final_response = result["messages"][-1].content
                st.markdown(final_response)
                
            except Exception as e:
                st.error(f"Execution Error: {str(e)}")