---
title: "Furrr ML"
output: html_notebook
---

```{r}
library(tidyverse)
library(future)
library(furrr)
library(recipes)
library(rsample)
library(keras)
library(tictoc)
```

```{r download data}
download_data <- function() {
    if (!file.exists("births_data.rds")) {
        download.file(
            "https://saturn-public-data.s3.us-east-2.amazonaws.com/birth-data/births_2005.rds",
            "births_data.rds"
        )
    }
    births_raw_data <- readRDS("births_data.rds")

    return(births_raw_data)
}
```

```{r filter data}
filter_data <- function(births_raw_data) {
    births_data <- births_raw_data %>%
        select(weight_pounds, is_male, plurality, mother_age, gestation_weeks)

    return(births_data)
}
```


```{r split data}
split_data <- function(births_data) {
    births_data_split <- births_data %>%
        initial_split(prop = 0.2)

    return(births_data_split)
}
```


```{r make recipe}
prepare_recipe <- function(births_data_split) {
    recipe_object <- births_data_split %>%
        training() %>%
        recipe(weight_pounds ~ .) %>%
        step_naomit(all_outcomes(), all_predictors()) %>%
        step_discretize(
            mother_age,
            options = list(cuts = 5, min_unique = 2)
        ) %>%
        step_discretize(
            gestation_weeks,
            options = list(cuts = 5, min_unique = 2)
        ) %>%
        step_dummy(all_nominal(), -all_outcomes()) %>%
        step_mutate(is_male = ifelse(is_male, 1, 0)) %>%
        step_center(all_predictors(), -all_outcomes()) %>%
        step_scale(all_predictors(), -all_outcomes()) %>%
        prep()

    return(recipe_object)
}
```


```{r define model}
define_model <- function(recipe_object,
                         layer1_units,
                         layer2_units,
                         layer1_activation,
                         layer2_activation) {
    input_shape <- ncol(
        juice(recipe_object, all_predictors(), composition = "matrix")
    )

    keras_model <- keras_model_sequential()

    keras_model %>%
        layer_dense(
            units = layer1_units,
            kernel_initializer = "uniform",
            activation = layer1_activation,
            input_shape = input_shape
        ) %>%
        layer_dropout(rate = 0.1) %>%
        layer_dense(
            units = layer2_units,
            kernel_initializer = "uniform",
            activation = layer2_activation
        ) %>%
        layer_dropout(rate = 0.1) %>%
        layer_dense(
            units = 1,
            kernel_initializer = "uniform",
            activation = "linear"
        ) %>%
        compile(
            optimizer = "adam",
            loss = "mse",
            metrics = list("mean_absolute_error")
        )

    return(keras_model)
}
```

```{r train model}
train_model <- function(recipe_object,
                        layer1_units,
                        layer2_units,
                        layer1_activation,
                        layer2_activation) {
    model <- define_model(
        recipe_object,
        layer1_units,
        layer2_units,
        layer1_activation,
        layer2_activation
    )

    x_train <- juice(recipe_object, all_predictors(), composition = "matrix")
    y_train <- juice(recipe_object, all_outcomes()) %>%
        pull()

    fit(
        object = model,
        x = x_train,
        y = y_train,
        batch_size = 1024,
        epochs = 2,
        validation_split = 0.2,
        verbose = 0
    )

    return(model)
}
```

```{r test results}
test_results <- function(births_data_split, recipe_object, keras_model) {
    testing_data <- bake(recipe_object, testing(births_data_split))
    X_test <- testing_data %>%
        select(-weight_pounds) %>%
        as.matrix()
    y_test <- testing_data %>%
        select(weight_pounds) %>%
        pull()
    results <- keras_model %>%
        evaluate(X_test, y_test)

    return(results)
}
```

```{r test model}
test_model <- function(births_data_split,
                       recipe_object,
                       layer1_units,
                       layer2_units,
                       layer1_activation,
                       layer2_activation) {
    model <- train_model(
        recipe_object,
        layer1_units,
        layer2_units,
        layer1_activation,
        layer2_activation
    )
    results <- test_results(births_data_split, recipe_object, model)
    tibble(
        mean_absolute_error = results[2],
        layer1_units = layer1_units,
        layer2_units = layer2_units,
        layer1_activation = layer1_activation,
        layer2_activation = layer2_activation
    )
}
```


```{r}
plan(multisession(workers = 6))
```

```{r}
births_raw_data <- download_data()
births_data <- filter_data(births_raw_data)
births_data_split <- split_data(births_data)
recipe_object <- prepare_recipe(births_data_split)

hyperparameters <- expand_grid(
    births_data_split = list(births_data_split),
    recipe_object = list(recipe_object),
    layer1_units = c(8, 16, 32),
    layer1_activation = c("relu", "sigmoid"),
    layer2_units = list(16),
    layer2_activation = list("relu")
)

###################################################
## Don't actually run this - it takes forever... ##
###################################################

# print("With purrr:")
# tic()
# results_purrr <- pmap_dfr(hyperparameters,test_model)
# toc()

# best_result_purrr <- results_furrr %>%
#   top_n(-1, mean_absolute_error) %>%
#   head(1)

#####################
## Run this instead##
#####################

print("With furrr:")
tic()
results_furrr <- future_pmap_dfr(hyperparameters, test_model)
toc()

best_result_furrr <- results_furrr %>%
    top_n(-1, mean_absolute_error) %>%
    head(1)

print(best_result_furrr)
```
```{r}
plan(sequential)
```

