# This opens a pull request everytime someone pushes to the release branch.

name: pull-request

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the branches that start with "release"
on:
  push:
    branches: "release*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "pull-request"
  pull-request:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Remove reference from recipe files
      run: python .ci/update-references.py
    - name: Diff recipes
      id: diff
      run: echo "::set-output name=result::$(git diff --quiet . || echo 'true')"
    - name: Commit new files
      if: ${{ steps.diff.outputs.result }}
      run: |
        git config --global user.name "saturn-automation"
        git config --global user.email "automation@saturncloud.io"
        git add *.json
        git commit -m "Remove reference in every recipe"
        git push origin ${{ github.ref }}:refs-main-${{ github.job }}
    - name: Open PR - with refs removed
      if: ${{ steps.diff.outputs.result }}
      uses: repo-sync/pull-request@v2
      with:
        source_branch: refs-main-${{ github.job }}
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Update main from release"
        pr_body: ":rocket: *An automated PR* - Please push an empty commit to trigger CI (don't squash merge)!"
        pr_reviewer: "forana,jsignell,${{ github.actor }}"
    - name: Open PR
      if: ${{ !steps.diff.outputs.result }}
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ github.ref }}
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Update main from release"
        pr_body: ":rocket: *An automated PR* - Please make any changes needed to resolve merge conflicts and then approve and merge (don't squash merge)!"
        pr_reviewer: "forana,jsignell,${{ github.actor }}"
