# This opens a pull request everytime someone pushes to the release branch.

name: pull-request

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the branches that start with "release"
on:
  push:
    branches: "release*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "pull-request"
  pull-request:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Update main from release"
        pr_body: ":rocket: *An automated PR* - Please make any changes needed to resolve merge conflicts and then approve and merge!"
        pr_reviewer: "forana,${{ github.actor }}"
        pr_draft: true
